run:
  #modules-download-mode: readonly
linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0
  gocognit:
    min-complexity: 30
  cyclop:
    max-complexity: 30
  fieldalignment:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  gosec:
    excludes:
      - G108
      - G114
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/fsnotify/fsnotify
          - github.com/getsentry/sentry-go
          - github.com/gin-gonic/gin
          - github.com/nikandfor/assert
          - github.com/nikandfor/hacked
          - github.com/opentracing/opentracing-go
          - github.com/prometheus/client_golang
          - github.com/prometheus/client_model
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require
          - go.opentelemetry.io/otel
          - golang.org/x
          - nikand.dev/go/cli
          - nikand.dev/go/graceful
          - tlog.app/go/eazy
          - tlog.app/go/errors
          - tlog.app/go/loc
          - tlog.app/go/tlog
  misspell:
  lll:
    line-length: 170
  goimports:
    local-prefixes: github.com/nikandfor/tlog
  prealloc:
    simple: true
    for-loops: true
  gocritic:
    enabled-tags:
      - experimental
      - performance
      - style
    disabled-checks:
      - appendAssign
      - appendCombine
      - builtinShadow
      - commentedOutCode
      - octalLiteral
      - unnamedResult
      - whyNoLint
      - yodaStyleExpr

linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - goerr113
    - golint
    - gomnd
    - ifshort
    - ireturn
    - lll
    - maintidx
    - maligned
    - nakedret
    - nestif
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - prealloc
    - predeclared
    - testpackage
    - thelper
    - typecheck
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
