version: 2
jobs:
  go1.16: &base
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/wd
    steps:
      - run: go version

      - checkout

      - run: go test -race -v ./...

  go1.15:
    <<: *base
    docker:
      - image: circleci/golang:1.15

  go1.14:
    <<: *base
    docker:
      - image: circleci/golang:1.14

workflows:
  version: 2
  build:
    jobs:
      - go1.16
      - go1.15
      - go1.14
